services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    network_mode: 'host'
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - type: bind
        source: /home/mm-2103/Videos
        target: /media
        read_only: true
    restart: 'unless-stopped'
